### ISSUE TITLE
How to recommend someone to interviewed?

### ISSUE THREAD

**Issue by naveensrinivasan** [linuxfoundation/lf-podcast#27]
What is the process for recommending someone to be interviewed? 

Is there a queue? Can that queue be public data? So that we can do a PR to it?

**Comment by mcleo-d** [comment]
Hi @naveensrinivasan 👋🏻 

It's great to hear from you and thank you for your great idea. I am looping @SeniorStoryteller into the conversation.

Feel free to raise your podcast suggestions using the `lf-podcast` GitHub Issues and I'll apply the new `podcast suggestion` label that we can review, prioritise and track.

I hope GitHub Issues work for you as they allow conversations to happen in the context of each issue. 

Thanks once again and speak soon,

James.

**Comment by SeniorStoryteller** [comment]
Thanks for jumping in James. Yes, the process we have planned is for people to make suggestions as PR. We're experimenting on how best to us GitHub as a community platform, and this process seems like it will work. -- Mark

**Comment by mcleo-d** [comment]
Hi @naveensrinivasan 

I am now closing this issue. Please feel free to make interview suggestions using the project GitHub Issues or add your own podcast episode via pull request.

FYI - I will update the docs soon to reflect the conversation above.

James.
